name: Webbower
tagline: Where healthy DOM trees are cultivated by Matt Bower
markdown: redcarpet
pygments: true
permalink: /blog/:title
exclude: [Gemfile, Gemfile.lock]
safe: true
lsi: false

# Google Analytics
ga-id: UA-18539289-1

# Social usernames
social:
  twitter: webbower
  github: webbower