name: Webbower
tagline: Where Matt Bower cultivates healthy DOM trees
markdown: redcarpet
pygments: true
permalink: /blog/:title
exclude: [Gemfile, Gemfile.lock]
# safe: true
lsi: false

# Google Analytics
ga-id: UA-18539289-1

# Social usernames
social:
  twitter: webbower
  github: webbower